### ISSUE TITLE
Support for FP32

### ISSUE THREAD

**Issue by houEricSY** [HazyResearch/flash-attention#13]
Thanks for the code of flash-attention, it's brilliant! But it seems that it doesn't support FP32 computation, I wonder how can I use flash-attention in FP32 setting.

**Comment by tridao** [comment]
We currently support Turing (e.g. RTX 2080) and Ampere (e.g. RTX 3080) GPUs. We rely on tensor cores for matrix multiplication, which older GPUs lack.
You might be interested in the memory-efficient attention implemented by the xformers team (targeting fp32 instead of fp16):
https://github.com/facebookresearch/xformers/pull/267
https://github.com/facebookresearch/xformers/pull/281

**Comment by fmassa** [comment]
Hi,

We have just pushed a PR in https://github.com/facebookresearch/xformers/pull/362 which contains V100 and P100 support as well, and dispatches to FlashAttention for the cases where it is supported.

**Comment by hypnopump** [comment]
## CONSORT Profiling: Softcap Value Changes and Kernel Recompilation

**Question**: Does changing the `softcap` value cause kernel recompilation?

**Answer**: No — different softcap values do **not** trigger recompilation. This is correct behavior.

### Profiling Results

Fresh cache (no disk cache), SM90 (Hopper), `(1, 64, 1, 128)` bf16:

| Call | Time | Notes |
|------|------|-------|
| `causal=True` (1st) | **2.87s** | Full compile |
| `causal=True` (2nd) | 0.3ms | In-memory cache hit |
| `causal=True, softcap=30` (1st) | **3.07s** | Recompile — `softcap is not None` changes compile key |
| `causal=True, softcap=30` (2nd) | 0.3ms | Cache hit |
| `causal=True, softcap=50` | **0.1ms** | No recompile — same compiled kernel |
| `causal=True, softcap=50` (2nd) | 0.1ms | Cache hit |
| `causal=True, softcap=30` (again) | 0.1ms | Still cached |
| `causal=False` (1st) | **1.77s** | New compile (causal flag differs) |
| `causal=False, softcap=30` (1st) | **2.05s** | New compile (non-causal + softcap variant) |
| `causal=False, softcap=50` | 0.3ms | No recompile |

### How It Works

The compile cache key in `interface.py` (line 690) uses `softcap is not None` (a boolean), not the actual softcap value:

```python
compile_key = (
    ...
    softcap is not None,   # line 690 — boolean, not the float value
)
```

The softcap value itself is stored as a runtime parameter on the kernel class (`self.softcap`, `self.inv_softcap = 1.0 / softcap`), passed to the kernel at launch time. This means:

- `softcap=None` → `softcap=30.0`: **recompiles** (boolean `False` → `True` in compile key — different code path)
- `softcap=30.0` → `softcap=50.0`: **no recompile** (both are `True` — same kernel, different runtime param)

### Compile Variants

There are **4 compile variants** for a given `(dtype, hdim, heads)` config:
1. `causal=True, softcap=None`
2. `causal=True, softcap=<any float>`
3. `causal=False, softcap=None`
4. `causal=False, softcap=<any float>`

### Verdict

**No bug.** Softcap value changes are correctly handled as runtime parameters without recompilation. Only the structural change (softcap enabled vs. disabled) triggers a recompile, which is expected since it changes the kernel code path.
