### ISSUE TITLE
[Question] What is the difference between FlashAttention and Memory Efficient Attention in xformers?

### ISSUE THREAD

**Issue by 00INDEX** [HazyResearch/flash-attention#175]
The paper I recently read, [SELF-ATTENTION DOES NOT NEED O(n2) MEMORY](https://export.arxiv.org/pdf/2112.05682v3.pdf), uses kernel fusion to overcome large GPU memory usage (to be more specifically, it avoids keeping the huge activation values of S and P during forward). 
So I want to know if this is very similar to what you do?

**Comment by tridao** [comment]
We included a detailed comparison in appendix B5 of the [paper](https://arxiv.org/abs/2205.14135).

**Comment by 00INDEX** [comment]
Thanks, I will check it .

**Comment by 00INDEX** [comment]
By the way, the block size for Query is min(M / 4 * d, d), why do we have to calculate a minimum? Can't it just be M / 4 * d?

**Comment by tridao** [comment]
We want S (size block_q * block_k) to fit in SRAM of size M. We choose block_k = M/(4 * d) so we want block_q <= O(d).
We also want one query block (size block_q * d) to fit in SRAM, so block_q <= O(M / d).
As a result, we want block_q <= O(min(d, M / d)).
We just pick the constant 4 so that the proof works out.

In practice the block sizes are picked to make implementation easier (e.g. always multiple of 16, always power of 2, etc.).

**Comment by 00INDEX** [comment]
OK, thanks.

**Comment by lms-mt** [comment]
$$ B_r = \frac{M}{4d} $$, is this constant 4 mannualy specified? isn't it because of four tiled parts: Q_i, K_j, V_j, O_i ? so multiply it with four?

**Comment by lms-mt** [comment]
> $$ B_r = \frac{M}{4d} $$, is this constant 4 mannualy specified? isn't it because of four tiled parts: Q_i, K_j, V_j, O_i ? so multiply it with four?

@tridao hi, glad to have your clue

**Comment by tridao** [comment]
Yes, that's right.

**Comment by lms-mt** [comment]
Thanks for confirming. @tridao
