### ISSUE TITLE
Questions about FusedDenseFunc

### ISSUE THREAD

**Issue by ftgreat** [HazyResearch/flash-attention#178]
FusedDenseFunc says "If process_group is not None and sequence_parallel=True, we're doing Tensor Parallel with sequence parallelism".
Tensor Parallel of dense layers are used for matrix weights as megatron mpu.
While sequence parallelism are used for norms & activations in this document https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/nlp/nemo_megatron/parallelisms.html. 

Would you please explain why these two parallelisms are combined, thanks in advance.

**Comment by tridao** [comment]
As mentioned in the docstring: "If process_group is not None and sequence_parallel=True, we're doing Tensor Parallel with sequence parallelism: we do an all_gather_raw of x before doing the matmul." 
If there's no sequence parallelism, then we don't need to do an all_gather.
If there is, then because of the layer preceding the dense layer (the layernorm) is sharded, we need to do an all gather.

The same flag is used in the original [implementation](https://github.com/NVIDIA/Megatron-LM/blob/3db2063b1ff992a971ba18f7101eecc9c4e90f03/megatron/core/tensor_parallel/layers.py#L329) from Megatron (and they have more docs on it there as well)
