### ISSUE TITLE
Questions about prenorm config of block module

### ISSUE THREAD

**Issue by ftgreat** [HazyResearch/flash-attention#216]
The prenorm of block is set True as default [flash_attn.modules.block](https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/modules/block.py#L40) . 

Besides performance purpose, will prenorm=True lead better converge vs regular prenorm?

Is there any experiments details about contrast of these two configs or paper references?

Thank you in advance.

**Comment by tridao** [comment]
This is just to control [pre-norm vs post-norm](https://arxiv.org/abs/2002.04745) architecture. Most recent models use pre-norm.
You can just look up pre-norm transformer.

**Comment by ftgreat** [comment]
> This is just to control [pre-norm vs post-norm](https://arxiv.org/abs/2002.04745) architecture. Most recent models use pre-norm. The way we implement it should yield exactly the same model architecture as commonly done. For example, we have [tests](https://github.com/HazyResearch/flash-attention/tree/main/tests/models) to check that GPT2, OPT, LLaMa, GPT-J, GPT-NeoX etc. implemented in this codebase give the same output as those implemented in HF transformers (up to numerical precision).

Thanks for your response.

The standard pre-norm block is: LN -> MHA -> Dropout -> Add -> LN -> MLP -> Dropout -> Add.
The flash-attention pre-norm block(when prenorm=True): Dropout -> Add -> LN -> MHA -> Dropout -> Add -> LN -> MLP

Still confused that why this implementation difference still give the same output?

**Comment by tridao** [comment]
It's about when you compose the blocks together.

Let's say there are 12 layers. A standard Transformer architecture, implemented using a standard pre-norm block:
Input embedding -> Emb Dropout -> [LN -> MHA -> Dropout -> Add -> LN -> MLP -> Dropout -> Add] x 12 -> LN -> Output embedding.

The way we implement the exact same architecture using the block in this repo:
Input embedding -> [Dropout -> Add -> LN -> MHA -> Dropout -> Add -> LN -> MLP] x 12 -> Dropout -> Add -> LN -> Output embedding.
The "Add" operation in the 0th layer will do nothing (as we pass in residual = None for the 0th layer), so this is exactly the same architecture as above.

**Comment by ftgreat** [comment]
Thank you very much. One more question, please.

In the running settings as follows: ddp zero3 without tensor parallel and sequence parallel.

Besides flash-self-atten and fused_dropout_add_ln, could you please list another skills used in current flash-atten llama implement for speedup & cuda mem reduction?

Thanks in advance.

**Comment by tridao** [comment]
Yeah that's about it.

**Comment by yt2639** [comment]
Hi @tridao, Thanks for the answers. I wanted to follow up on this: 

1. If we don't use the fused `dropout_add_norm`, i.e. `fused_dropout_add_ln=False`, will the performance (NOT about speed or memory) be the same when comparing the **standard** and **this code's** way of implementing pre-norm? Specifically, I implement the standard way using functions and modules in this repo:
```
[LN -> Flashattn-MHA -> Dropout -> Add -> LN -> FusedMLP -> Dropout -> Add] x 12
```
Will this one affect the performance (NOT about speed or memory)?

2. Additionally, if we don't use `fused_dropout_add_ln` and implement the block by the standard pre-norm way (as shown above), but use `fusedMLP`, will this cause any performance drop? Essentially, do we need to consistently use one set of functions, regarding `fused_bias_fc`, `fusedMLP`, `fused_add_norm_fn`, etc. I assumed they only affect run speed instead of performance. Is this understanding correct?

Thanks!

**Comment by tridao** [comment]
Correct, it's only about speed.
