### ISSUE TITLE
about mask is_valid check method

### ISSUE THREAD

**Issue by lw921014** [HazyResearch/flash-attention#24]
Hi,
I want to ask some details for [mask](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha/mask.h#L38) .

My related parameter is head dim is 32, seq len q = 64, seq len k = 64. I use ampere SM80 arch, so the compute tensor core is m16n8k16. 

About the mask constructor and check method, I have two question:
1. about comput col [here](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha/mask.h#L54), I do not know what the 16 means? Acording to my understand, for our config, we will use 4 warps to compute a tile block( m = 16, k = 32, n = 128), and each warps will compute N = 32 colums, so if here we when comput offset of col, I think should be
`col = warp_n * 32 + tid;`, do you think it correct?

2. about is_valid method. Can you tell me what is the basic logic of this [formular](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha/mask.h#L61)

3. also about is_valid method. When we [return the result](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha/mask.h#L69), would it be possible for you to tell me what this condition mean? Why should we compare current_col with current_row?
`current_col + loop_step_idx * Cta_tile::N <= current_row`

Thanks a lot and thanks for your great job.

**Comment by tridao** [comment]
The mapping between thread ids and indices are unfortunately a little complicated, since we're using tensor core (m16n8k16 instruction on SM80).
I've found the best way to verify all the indexing is to print out (with printf) the mapping of threads id to the columns and rows.

1. & 2. For the purpose of discussion, assume that seqlen=128 so we process 128 columns at a time.
In the forward pass, we use 4 warps.
- For each iteration, we process 16 rows and 128 columns, with each warp processing 16 rows and 32 columns. The unit block we operate on is 16x16, so you can imagine the 16 x 128 elements being divided into 8 blocks.
The mapping between warp index and block index is:
[0, 1, 2, 3, 0, 1, 2, 3]
i.e., warp 0 processes block 0 and 4, warp 1 processes block 1 and 5, etc.
`ni` (either 0 or 1) denotes which block the warp is processing (block 0 or block 4, block 1 or block 5, etc). That's why to compute `current_col` we first add `ni * Mma_tile::N_PER_MMA_PER_CTA` which is `ni * 64` in this case.
`col` is then `warp_n * 16 + tid`, which points you to the right block.
- Within each 16 x 16 block, we follow the layout of the m16n8k16 accumulation output (with two such 16x8 outputs side-by-side).
`jj` goes from 0 to 3, which will tell you which column within that block.

Let me know if this doesn't make sense.

3. Comparing current_col and current_row is only applicable for causal mask (query i will only attend to key 0, 1, ,..., i).

**Comment by lw921014** [comment]
> Let me know if this doesn't make sense.

It really help me a lot. Thank a lot.
