### ISSUE TITLE
Any plan to continue cutlass (re)implementation of flash attention

### ISSUE THREAD

**Issue by pommedeterresautee** [HazyResearch/flash-attention#30]
I am currently studying cutlass and saw you started to (re)implement this project with cutlass abstractions.
My understanding is that today it's partially done, and I am wondering if you met some blocker because somehow you absolutely need lowest level CUDA code (if yes, would it be possible for you to share those?) or still plan to finish this task.

Thank you for this project, it's super interesting!

**Comment by tridao** [comment]
Yes, it's partially done, and I plan to finish it. I just haven't had as much time / bandwidth as I would like.
My understanding is that Cutclass should not bring any overhead (many of the matrix multiply operations in cuBLAS actually call Cutlass).

Currently the warp matrix multiply instruction is done by calling Cutlass. The next step is to rewrite the shared memory reading/writing to use Cutlass iterators.

**Comment by pommedeterresautee** [comment]
Thanks for your fast answer!

**Comment by tridao** [comment]
You can check out the `cutlass` branch where we've rewritten the forward pass to use cutlass.

**Comment by pommedeterresautee** [comment]
thank you for the notification. 
May I ask you how you found your experience with cutlass library? (compared to Cuda and Triton if you use the 2nd one)
My team had a hard time with the many templates and concepts from cutlass, on the other side we learned quite a lot about some optimizations by reading the code...

**Comment by tridao** [comment]
There's quite a bit of a learning curve for sure. Took me a while to figure out which classes to use (I'm still not sure if I'm using exactly the right thing).
The cutlass devs are quite responsive to questions on github so that helps.

Cutlass abstracts away some of the trickiest bits (e.g., reading/writing to shared memory) so for me it was worth it to invest the time.

I haven't played with Triton too much. My impression is that under the hood the Triton compiler implements similar shared memory reading/writing. You're just programming at a different level of abstraction where these details are hidden away.

Cutlass might be more mature and battle-tested (e.g., some of the cuBLAS gemm calls dispatch to Cutlass kernels).

**Comment by pommedeterresautee** [comment]
Thank you for your answer. It's very insightful.

FWIW, regarding Triton, we are playing with it, it's super productive compared to cuda / cutlass, but sometimes (rarely) you need some crazy workaround that doesn't make any sense (like in Flash attention implementation, it writes to GM to force the compiler to add instructions to redistribute work among threads), so definitely less mature. My understanding is that, like any tech, things are gonna improve soon :-)
