### ISSUE TITLE
Support for Pascal architecture GPUs

### ISSUE THREAD

**Issue by DwayneX77** [HazyResearch/flash-attention#32]
Wonderful work presented! May I ask if there is any plan to expand support list to include Pascal architecture GPUs? Take Tesla P-Series as examples.

**Comment by tridao** [comment]
We currently support Turing (e.g. RTX 2080) and Ampere (e.g. RTX 3080) GPUs. We rely on tensor cores for matrix multiplication, which older GPUs lack.
You might be interested in the memory-efficient attention implemented by the xformers team (targeting fp32 instead of fp16), which I believe supports Pascal cards:
https://github.com/facebookresearch/xformers/pull/267
https://github.com/facebookresearch/xformers/pull/281

**Comment by DwayneX77** [comment]
Thanks! Your advice helps a lot.

> We currently support Turing (e.g. RTX 2080) and Ampere (e.g. RTX 3080) GPUs. We rely on tensor cores for matrix multiplication, which older GPUs lack. You might be interested in the memory-efficient attention implemented by the xformers team (targeting fp32 instead of fp16), which I believe supports Pascal cards: [facebookresearch/xformers#267](https://github.com/facebookresearch/xformers/pull/267) [facebookresearch/xformers#281](https://github.com/facebookresearch/xformers/pull/281)

**Comment by fmassa** [comment]
Hi,

We have just pushed a PR in https://github.com/facebookresearch/xformers/pull/362 which contains V100 and P100 support as well, and dispatches to FlashAttention for the cases where it is supported.

**Comment by ifffrt** [comment]
> Hi,
> 
> We have just pushed a PR in [facebookresearch/xformers#362](https://github.com/facebookresearch/xformers/pull/362) which contains V100 and P100 support as well, and dispatches to FlashAttention for the cases where it is supported.

Would this PR make support for Maxwell GPUs possible as well?
