### ISSUE TITLE
Support for Kaggle P100 GPU

### ISSUE THREAD

**Issue by pchankh** [HazyResearch/flash-attention#4]
First and foremost congratulation of a great R&D work here. Wonder if there is any plan to support Kaggle GPUs?
I suspect there will be a great deal of interest from the community there to test this.

Cheers
Dr.Patrick

**Comment by tridao** [comment]
Thanks for the interest!
We're currently prioritizing support for Turing (T4) & Volta (V100) architectures as mentioned in the roadmap.
We've been talking to the xformers team and they're also working on something similar (targeting fp32 instead of fp16).
There's a chance we might be able to borrow what they have to support P100 eventually.
https://github.com/facebookresearch/xformers/pull/267
https://github.com/facebookresearch/xformers/pull/281
