### ISSUE TITLE
Support for 256 head dim

### ISSUE THREAD

**Issue by Sanger2000** [HazyResearch/flash-attention#67]
Really love this repo, I've been using it to finetune CodeGen models with >2k context windows.

It's way faster than hugging face (3x) and slightly faster than Megatron for the 350M and 2.7b parameter CodeGen models but doesn't work for the 6.1B and 16B parameter models as they have a head dimension of 256.

<img width="1006" alt="Screen Shot 2022-11-01 at 5 32 47 PM" src="https://user-images.githubusercontent.com/17725268/199345886-f8b7531e-9918-4fba-ab37-4ae980ec2796.png">

I would imagine CodeGen finetuning will be a solid use-case for flash attention since coding models can really benefit from long context windows. And CodeGen is basically SOTA for coding (competitive with Codex).

Is this something that is even possible with flash attention?

**Comment by tridao** [comment]
Thanks for the kind words! I agree that code generation is a great use case!

We haven't been able to get speedup on headdim=256. In order to reduce memory reads/writes, we load some block of Q, K, V from GPU memory to SRAM, and SRAM size is the main constraint (e.g. 163 KB per streaming multiprocessor on A100). As head dimension gets large, we can't fit the block into SRAM without making the block size very small, and thus making the whole computation slower.

For now we support head dimension up to 128.

**Comment by Sanger2000** [comment]
Ahh, yeah I see. Looks like I'll have to find another pretrained code model to use for long sequences 😔

Again this code has been fantastic. My mind was blown when I saw how high I could set batch sizes without running out of memory.

**Comment by ZhongYingMatrix** [comment]
> (e.g. 163 KB per streaming multiprocessor on A100)
Hi, is SRAM on A100 163KB or 192KB. I notice the latter in paper

**Comment by tridao** [comment]
The [total](https://en.wikipedia.org/wiki/CUDA#Technical_Specification) SRAM per multiprocessor is 192KB, but only 163KB is usable for the programmer (the remaining is L1 cache I believe).

**Comment by ZhongYingMatrix** [comment]
Thanks for reply~

**Comment by ZhongYingMatrix** [comment]
Thanks for your reply~
So can we assume that M in the paper is 163 * 1024 = 166912, and B_c = M/4/d (assume d=64) = 652 while B_r = 64?
I'm kind of confused cause the B_c and B_r are both fixed 128 in the triton version, and I have not figured out where the Cuda version config them. Is it alright only if the SRAM can hold it no matter how we set B_c/B_r?

**Comment by tridao** [comment]
In practice the block sizes are set to optimize for speed and ease of implementation. For example, the Triton version set block sizes to (128, 128) because that's what the Triton compiler support (other shapes will lead to wrong results or compiler error). As another example, block sizes are always powers of 2, otherwise it's much harder to implement.
The CUDA version sets B_c = 128 or 256, and B_r = 16.
For example, the dispatch [here](https://github.com/HazyResearch/flash-attention/blob/908a5b2244850fb299d22a23345723e61b0c4613/csrc/flash_attn/src/fmha_fprop_fp16_kernel.sm80.cu#L129) corresponds to B_c = 256 and B_r = 16.

**Comment by tridao** [comment]
I have not implemented anything for headdim > 128 (it takes effort to implement the low-level shared memory loading/writing for different head dimensions, for best efficiency).
If you have info on this that would be very helpful.

**Comment by shijie-wu** [comment]
Thanks! I don't have any info on this as well. I assumed that it's not supported because you have tried it and the result is mixed. We will explore it when we get a chance.

**Comment by tridao** [comment]
As of v2 we support all head dimensions up to 256. Head dim > 192 backward requires A100/A800 or H100/H800.
