### ISSUE TITLE
Support for RTX 4090 (Ada Lovelace arch)

### ISSUE THREAD

**Issue by ywalterh** [HazyResearch/flash-attention#79]
Hi team, amazing work so far!

I'm curious if Ada Lovelace support is on the roadmap? Running the code on RTX 4090 generates expected error message:
```
  File "/home/walterh/.conda/envs/photodream/lib/python3.8/site-packages/flash_attn-0.2.1-py3.8-linux-x86_64.egg/flash_attn/flash_attn_interface.py", line 41, in _flash_attn_backward
    _, _, _, softmax_d = flash_attn_cuda.bwd(
RuntimeError: Expected is_sm80 to be true, but got false.
```

If this is something I can help with, please let me know. Happy to contribute too.

**Comment by tridao** [comment]
I think it should be easy to support the RTX 4090. The current code should work, or one might just need to add a compilation flag for sm_89 in `setup.py`.

I think the error you're running into is because the backward pass for headdim > 64 requires A100 (or H100 when that comes out). It needs a lot of SRAM / shared memory that other GPUs don't have.

I don't have the hardware to test it right now, but if you have an RTX 4090 can you try running the forward pass and backward pass for headdim <= 64?

**Comment by ywalterh** [comment]
Thanks for the prompt reply! That was indeed what the issue was, I didn't even realize I have some Attention with dim_head at 80. Which explains why T4 didn't work and A100 worked in Colab. 

After making the change, I can confirm that it works just fine with RTX 4090. Thank you guys again!

Also, out of curiosity, from the paper I didn't see anything obvious why it doesn't work with fp32. Is that something FlashAttention can support in the future?

**Comment by ywalterh** [comment]
Memory efficiency is a huge gain too. I'll check them out. Thanks for the additional information and feel free to close the issue.
