### ISSUE TITLE
Question about flash attention dropout

### ISSUE THREAD

**Issue by SeaOfOcean** [HazyResearch/flash-attention#93]
Hi

I noticed that with attention dropout, besides dropout for P, in the final write, there is code as follows
```
for (int jj = 0; jj < Gmem_tile_o::STGS_PER_LOOP; jj++) {
            float sum = p_sum_o[jj][0];
            float inv_sum = (sum == 0.f || sum != sum) ? 1.f : 1.f / sum;
            if (Is_dropout && is_final_write) {
                inv_sum *= params.rp_dropout;
            }
            out[jj] = fmha::fmul4(out[jj], inv_sum);
        }
```

https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha_fprop_kernel_1xN.h#L629

same for backward https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha_dgrad_kernel_1xN_loop.h#L689

I did not find it in the paper

![image](https://user-images.githubusercontent.com/10606312/208626490-227d7095-1e13-41f3-a7b9-64e9f1ab4912.png)

**Comment by tridao** [comment]
To dropout a tensor with probability p, one zeros out a fraction p of the entries, and then multiply the rest of the entries by 1/(1 - p).
In the paper, we denote these 2 steps as "dropout".
In the code, we separately zero out a fraction of the matrix P. Then instead of scaling P by 1 / (1 - p) before multiply P with V, we multiply P with V first to get the output, then scale the output by 1 / (1 - p). This is mathematically equivalent.

**Comment by SeaOfOcean** [comment]
what's the reason for this change? for speed or numerical stable?

**Comment by SeaOfOcean** [comment]
I also noticed that in this commit, Apply dropout scaling to dQ and dK instead of to V (in bwd), will it help better training stability?
https://github.com/HazyResearch/flash-attention/commit/5b838a8bef78186196244a4156ec35bbb58c337d

**Comment by tridao** [comment]
> what's the reason for this change? for speed or numerical stable?

For speed, since applying dropout scaling to output will result in fewer floating point ops than applying dropout scaling to P. However, the speed difference is probably minimal (< 1%).

> I also noticed that in this commit, Apply dropout scaling to dQ and dK instead of to V (in bwd), will it help better training stability?
https://github.com/HazyResearch/flash-attention/commit/5b838a8bef78186196244a4156ec35bbb58c337d

I don't think it affects stability. I didn't see any change to numerical error between the two versions.

**Comment by SeaOfOcean** [comment]
In previous dropout version, what's the reason for     " Instead of scaling dP by rp_dropout, we scale V instead " https://github.com/HazyResearch/flash-attention/blob/a5559a0e752ec9f8ce7157e1d4db9f08593638c3/csrc/flash_attn/src/fmha_dgrad_kernel_1xN_loop.h#L220

**Comment by tridao** [comment]
They're mathematically equivalent. 
We want dP = rp_dropout * dO * V^T, so we can either multiply dO * V^T then scale the result by rp_dropout. Or we scale (rp_dropout * V^T) first before multiply by dO. The 2nd way results in fewer floating point ops (though the speed difference is probably < 1%). I removed it just so all the scaling are done in fp32 (which ended up not mattering when it comes to numerical error).

**Comment by SeaOfOcean** [comment]
Thanks for the nice and detailed explanation!

**Comment by SeaOfOcean** [comment]
![image](https://user-images.githubusercontent.com/10606312/208811736-434c7b54-80f2-4194-bac1-35e3258eef2c.png)

Another question, what's the code corresponding line:18 in algorithm?

**Comment by tridao** [comment]
There's a trick in the implementation here to save storage: 
This [line](https://github.com/HazyResearch/flash-attention/blob/a5559a0e752ec9f8ce7157e1d4db9f08593638c3/csrc/flash_attn/src/fmha_dgrad_kernel_1xN_loop.h#L327) generates the dropout mask and stores the dropout mask as sign of the elements in P (e.g. we store 0.1 if attention prob is 0.1 and the corresponding dropout mask is 1, we store -0.2 if attention prob is 0.2 and the corresponding dropout mask is 0).

This [block](https://github.com/HazyResearch/flash-attention/blob/a5559a0e752ec9f8ce7157e1d4db9f08593638c3/csrc/flash_attn/src/fmha_dgrad_kernel_1xN_loop.h#L392) of code corresponds to line 18 and 20: if the value we store in p is negative, then we get ds = p * d (i.e., -attn_prob * d), because it corresponds to dropout mask being zero. If the value we store in p is positive, then we get ds = p * acc_dp (i.e., attn_prob * (dp - d)), since it corresponds to dropout mask being 1.

Later on when we need to use P we take [relu](https://github.com/HazyResearch/flash-attention/blob/a5559a0e752ec9f8ce7157e1d4db9f08593638c3/csrc/flash_attn/src/fmha_dgrad_kernel_1xN_loop.h#L476) to remove the dropout mask that was being stored as sign of P.

If you want to implement it it's probably simpler to store the dropout mask separately without this trick.
