### ISSUE TITLE
why compare p_prev_lse with current max?

### ISSUE THREAD

**Issue by ofhwei** [HazyResearch/flash-attention#99]
hi, thank you for your great work. And I have a question while I'm learning these codes: [in the origin code](https://github.com/HazyResearch/flash-attention/blob/main/csrc/flash_attn/src/fmha_fprop_kernel_1xN.h#L433) `p_max[mi] = p_prev_lse[mi] / params.scale_bmm1f;`, i think it should be `p_prev_max` instead of `p_prev_lse` here to compute the new max value, as the `p_prev_lse` stores the previous columns' `max + log(sum)`.    I'm confused here why use `p_prev_lse` here, could you please tell me more details , thanks😊

**Comment by tridao** [comment]
Either updating with `p_prev_max` or `p_prev_lse` is fine, they both produce correct results.
For numerical stability, to compute softmax, one first subtracts a constant to ensure that the exponentiation doesn't overflow. This constant is often chosen to be the max, so that after exponentiation the value is at most 1. For our setting, this should be max(max of current block, max of previous block), exactly as you mentioned.
One can also choose a different constant. In the code I chose to subtract by max(current_max, LSE of previous block).
This is easier to implement since we only need to store the LSE of each block.
One can also of course store both the max and the LSE, as written in the paper.

**Comment by ofhwei** [comment]
Thanks for your reply, I understand the question now ^_^.
